name: Build

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

env:
  AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
  AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
  AZURE_USER: ${{ secrets.AZURE_USER }}
  GITHUB_PAT: ${{ secrets.GH_TOKEN }}
  GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
  GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
  GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
  GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
  GPR_USER: ${{ secrets.GPR_USER }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
  WYAM_DEPLOY_BRANCH: "gh-pages"
  WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .net
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          # gitReleaseManager needs 3.1, gitVersion needs 5.0
          dotnet-version: |
            3.1.x
            5.0.x
            7.0.x
      - name: Cache Tools
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build project
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1.4.1
        with:
          script-path: recipe.cake
          target: CI
          cake-version: tool-manifest
      # currently, Cake.Recipe does not upload artifacts when run on gh-actions
      - name: Upload Issues
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        if: runner.os == 'Linux'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*
